### ISSUE TITLE
How to decompile a named function?

### ISSUE THREAD

**Issue by pinkfrog9** [clojure-goes-fast/clj-java-decompiler#11]
For example,
```
(decompile some-fn)
```
decompiles into invoking `some-fn` instead of showing the content of some-fn.

**Comment by alexander-yakushev** [comment]
clj-java-decompiler cannot decompile functions by their name due to how it works. Please see https://github.com/clojure-goes-fast/clj-java-decompiler#comparison-with-nodisassemble.

> If you are using CIDER, you can jump to the definition of the function you want to decompile and call M-x clj-decompiler-decompile on it. Alternatively, if you don't use clj-decompiler.el, you can disable read-only mode (C-x C-q) in the buffer of the existing function you want to decompile, wrap the defn form with clj-java-decompiler.core/decompile and recompile the form (C-c C-c).
