### ISSUE TITLE
Output doesn't show up in my Emacs repl

### ISSUE THREAD

**Issue by vemv** [clojure-goes-fast/clj-java-decompiler#3]
Hi!

Neat project, kudos.

I noticed I can only see the useful part of the output (as opposed to `// Decompiling class:`) in `lein repl`, but not in my CIDER repl.

Perhaps relatedly, even in `lein repl` there's the weirdeness that I can't capture the output with `with-out-str`.

It would be useful to be able to `(spit "foo" (with-out-str (decompile ...)))`.

Thanks - Victor

**Comment by alexander-yakushev** [comment]
Hi, thanks for reporting! I could reproduce the problem with the latest CIDER, apparently, some recent CIDER changes broke this.

I pushed the fix with `0.2.1-SNAPSHOT`, could you please try it out? It also fixes the latter with-out-str problem you mentioned.

**Comment by vemv** [comment]
Hey there,

tried out both. Working! 🍻

**Comment by alexander-yakushev** [comment]
Cool! I released `0.2.1` with the fix. Thanks!
