### ISSUE TITLE
Running the decompiler alters var metadata

### ISSUE THREAD

**Issue by vemv** [clojure-goes-fast/clj-java-decompiler#7]
Hi!

I found out that running the decompiler for a given `defn` can alter its var's metadata:

```clj
(meta #'my/var) ;; => {:file "cjd.clj", ...}
```

This can break IDE features, like jump-to-def.

Can this be prevented?

Thanks - V

**Comment by alexander-yakushev** [comment]
Hi, the metadata is different because the form ha to be compiled in a separate virtual file. Why is this a problem for you, do you leave `(decompile ...)` form in the code after you are done with it?

**Comment by vemv** [comment]
>  do you leave (decompile ...) form in the code after you are done with it?

Nope, but if the code was third-party, then I will not be able to reach it.

You are right in that if the `decompile`d code was mine, it would be simply a matter reloading it.

**Comment by alexander-yakushev** [comment]
Sorry, I'm confused. What exactly are you trying to do and what is the problem? Are you using some third-party code that wraps a definition into `decompile`?

**Comment by vemv** [comment]
Sorry for the lack of context. Here's a more specific example:

```clj
(ns foo ;; <- inside my `clojure.tools.namespace.repl/refresh-dirs`
  (:require
   [third-party]  ;; <- outside my clojure.tools.namespace.repl/refresh-dirs`
))

(comment ;; from the repl:
  (clj-java-decompiler.core/decompile third-party/something))
```

That would, sometimes, alter the `#'third-party/something` metadata.

However I'm having trouble creating a reprodudible case. In any case, this morning I certainly got ` {:file "cjd.clj", ...}` into a third-party var, which kind of spoiled my REPL session, forcing me to restart the JVM.

**Comment by alexander-yakushev** [comment]
I see. Well, first of all, `(decompile third-party/something)` doesn't decompile the third-party function (which was probably what you wanted from it), it tries to decompile **the var of the third-party function** which doesn't make much sense. Now, if you did that and want to restore it, you can call `(require '[third-party :reload-all true])` to reload the namespace. It will fix the metadata.

Now, to actually decompile a third-party function, you would need an editor/IDE that is able to jump into code in dependencies. E.g., in Emacs/CIDER, you can jump to definition of `third-party/something`. It would open a read-only buffer of the namespace with that function; but you can flip the read-only flag with `C-x C-e`, then wrap the definition of the function into `(clj-java-decompiler/decompile ...)` and execute it. When done, you unwrap the function, recompile it, and now everything is clean again.

**Comment by vemv** [comment]
> Well, first of all, (decompile third-party/something) doesn't decompile the third-party function (

Yes, sorry I was struggling to recall the exact scenario that triggered the original issue. My examples indeed don't repro anything.

Now I got to reproduce it:

* Jump to the definition of `third-party/something`
* Decompile `(defn something ...)`
* Jump back to one's own namespace
  * Now I won't be able to jump to `third-party/something` again

---

I think that both the `(require '[third-party :reload-all true])` and `you unwrap the function, recompile it, and now everything is clean again` suggestions are quite on point.

At the same time the former is a bit hard to remember (I use Reloaded so `:reload-all` is abstracted away), and the latter seems a manual step that would be compensating for a lack of cleanup from CJD's side.

Isn't it possible to automate the cleanup?

Thanks - V

**Comment by alexander-yakushev** [comment]
You should have begun with this. Like I've written before, `(require '[third-party :reload-all true])` should fix it. Either that, or jump to the namespace itself, remove the decompile form and recompile.

**Comment by vemv** [comment]
> You should have begun with this. 

Well I had trouble remembering the exact failing scenario, so I opened the issue in hope that you would know the nature of the problem already

> Like I've written before, (require '[third-party :reload-all true]) should fix it. Either that, or jump to the namespace itself, remove the decompile form and recompile.

These suggestions don't address the fact that CJD, in a way, pollutes Clojure's runtime environment.

Are you open to improvements so that users don't have to remember or implement workarounds? 

Thanks - V

**Comment by alexander-yakushev** [comment]
> Are you open to improvements so that users don't have to remember or implement workarounds?

Sure! I'm certainly open to pull requests that address that.

**Comment by vemv** [comment]
> Sure! I'm certainly open to pull requests that address that.

Alrighty! I might give it a shot these days, anyway I'll close the issue for keeping the tracker leaner.
