### ISSUE TITLE
[suggestion] Add reference to new decompiler Emacs package

### ISSUE THREAD

**Issue by bsless** [clojure-goes-fast/clj-java-decompiler#8]
Hello,
I wrote a small Emacs package to interact with clj-java-decompiler. It allows the user to send a form at point to be decompiled in the REPL and displayed in a temporary buffer.
I found it improved my workflow with the decompiler greatly to have such an immediate feedback loop.
I was wondering if you'd like to add a reference to it for Emacs users.
https://github.com/bsless/clj-decompiler.el

Thanks

**Comment by alexander-yakushev** [comment]
Hello Ben, this is great! I've been using something like that personally for some time, albeit much hackier, so I never got to properly publish it. Thank you for doing this! I will add the reference to your project right away.

**Comment by alexander-yakushev** [comment]
Done!

**Comment by bsless** [comment]
Thanks! It's my pleasure. Wouldn't have been possible without standing on the shoulders of giants :smile: 
I merely wired a few pieces together and went through the bother of packaging it nicely

Your libraries have been wonderful and useful tools in my experience with Clojure. Keep it up :)

**Comment by alexander-yakushev** [comment]
Thank you for kind words! We all do stand on the shoulders of giants, those libraries are mostly just wrappers around the actual hard work that other people did 😄.
